### ISSUE TITLE
Can the code perform as SAM do if I set the parameter "adaptive" false in the ESAM.py?

### ISSUE THREAD

**Issue by azazazaz123456** [dydjw9/Efficient_SAM#7]
![图片1](https://github.com/dydjw9/Efficient_SAM/assets/129163369/79307ca0-6f3c-4314-bda8-93db234526d3)
just in the init part.
Because when I set "adaptive" as false, the result for Cifar100 and WRN-28-10 is different from the result you posted in your paper, whose accuracy is 84.07 while yours is 83.42±0.04.
Is there anything wrong? Shell I change other part of your code ?

**Comment by dydjw9** [comment]
Hi, 
Thanks a lot for following our work. 
As we modify the sam.py from https://github.com/davda54/sam, it should work the same as SAM if you set adptive as True. However, we did not use the adaptive=True in our experiments. 

As for the performance difference, i guess it may be due to the mutilple GPUs setting or the setting of random seed. I think 84.07 is a reasonal results and there is no need to change other parts of the code.
Best

**Comment by azazazaz123456** [comment]
Are there some mistakes? The "adaptive" is for ASAM, so I think if the value is False, the code will perform as SAM does.

**Comment by dydjw9** [comment]
Hi,
The adaptive will only control the magnitude of rho, therefore it is okay to set it False. We also used the adaptive=False in our experiments.
Best

**Comment by azazazaz123456** [comment]
Thanks for your patient answer, I know what you mean. 
Best wishes
